# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool: 'laptops'

stages:
  - stage: windows_latest
    displayName: 'windows-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: Test
        displayName: 'Test'
        dependsOn: [  ]
        strategy:
          parallel: 4
        steps:
          - task: Cache@2
            inputs:
              key: $(Agent.OS) | **/global.json, **/*.csproj
              restoreKeys: $(Agent.OS)
              path: ~/.nuget/packages
          - task: CmdLine@2
            inputs:
              script: './build.cmd Restore Compile Test --skip --partition $(System.JobPositionInPhase)/4'